### ISSUE TITLE
IndexError on race start

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/dr2_logger#13]
happens rarely for me:

Race starting: BMW M2 Competition on PL, Leczna, Borysik
Cleared 4563 data points
Race Logger |----------------| Time: 00:00, ETA: 29:12, Speed: 0.0 m/s, RPM:     0, Samples: 00000, racing
Traceback (most recent call last):
  File "dr2_logger.py", line 138, in <module>
  File "dr2_logger.py", line 129, in main
  File "source\logger_backend.py", line 271, in check_state_changes
  File "source\dirt_rally\game_dirt_rally.py", line 162, in get_race_duration
IndexError: index -1 is out of bounds for axis 1 with size 0
[2476] Failed to execute script dr2_logger

looks like some clean-up conflicts with starting a new race

**Comment by ErlerPhilipp** [comment]
done in release_1.8.2
