### ISSUE TITLE
Error in get_game_state_str

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/dr2_logger#14]
Race starting: Ford Fiesta OMSE SuperCar Lites on RX, ES, Barcalona-Catalunya
Cleared 18755 data points
Race Logger |----------------| Time: 00:08, ETA: 16:08, Speed: 25.2 m/s, RPM:  6545, Samples: 00518, racingTraceback (most recent call last):
  File "dr2_logger.py", line 138, in <module>
  File "dr2_logger.py", line 91, in main
  File "source\logger_backend.py", line 158, in get_game_state_str
  File "source\dirt_rally\game_dirt_rally.py", line 77, in get_game_state_str
OSError: [Errno 22] Invalid argument

maybe specific for RX

**Comment by ErlerPhilipp** [comment]
probably done in release_1.8.2
